[package]
name = "bkeep"
version = "0.1.0"
authors = ["vedangj044 <vedangj044@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.7", features = [ "mysql" ] }
dotenv = "0.15.0"